### ISSUE TITLE
Request fields in add attachment

### ISSUE THREAD

**Issue by urtson** [geocollections/sarv-file-upload#10]
1. 'imageset_id' should be 'imageset' as this is correct field name in django models
2. It is not needed to request fields 'image_number','user_added','user_changed','date_added','date_changed','database_id','uuid','uuid_filename','filename','date_created'
These fields are filled automatically and right now I have to hardcode to skip them if they come in the request

**Comment by enmust** [comment]
Done. 
You should also clear your local storage so that the existing storage won't override new values. 

Currently date_created field is connected with date input.
Shouldn't user be able to choose a date, for example if it is old picture and user wants to choose any date.

**Comment by urtson** [comment]
You are right, date_created should be keeped

'imageset' was missing in config_add, this probably caused the error. Should be ok now

**Comment by enmust** [comment]
ok, now it is 'imageset' but api gave some kind of error

**Comment by urtson** [comment]
Can you post the error?

**Comment by urtson** [comment]
Fixed
