### ISSUE TITLE
Change view ready for testing

### ISSUE THREAD

**Issue by urtson** [geocollections/sarv-file-upload#12]
https://rwapi.eurocore.rocks/change/attachment/
POST id=$id&etc.

**Comment by ollehints** [comment]
Why not use PUT/PATCH which are the conventional way for full and partial UPDATE query in REST?
Then the address would be https://rwapi.eurocore.rocks/change/attachment/121367

**Comment by urtson** [comment]
If I open change view by clicking on ID on My Files page the view is empty, only the header is displayed e.g. 'Attachment 121402'

**Comment by enmust** [comment]
Now should be okay
