### ISSUE TITLE
Action after file upload

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#17]
After file(s) have been successfully uploaded, direct user to the list of photos (https://upload.eurocore.rocks/#/edit) by default. Later, additional behaviors could be added to make working easier, e.g., [save and add another], [save and continue editing]

**Comment by enmust** [comment]
Now after successful upload user is redirected to .../#/edit

**Comment by enmust** [comment]
Added button 'save and continue editing'
