### ISSUE TITLE
Filters in edit view

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#18]
Edit view (https://upload.eurocore.rocks/#/edit) should have some simple icontains filters:
* image_number
* original_filename OR uuid_filename
* specimen_id OR specimen__specimen_id
* description OR image_place OR image_object OR image_people OR image_description OR tags

**Comment by enmust** [comment]
+ locality search (locality, locality_en)

**Comment by enmust** [comment]
Updated filters
