### ISSUE TITLE
Add attachment links

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#19]
Add "Other files" functionality should have an option to include links to other database objects via attachment_link table. The relations are to: 
- collection
- specimen
- sample
- sample_series
- analysis
- dataset
- doi
- locality
- drillcore
- drillcore_box
- preparation
- reference
- storage

The UI should be discussed. A subform as in sarv.geokogud.info is not the best way. Maybe adding relations could be done via two combos: one for related table name and the other for name / ID value pair. The second one would then be populated/initiated only once the table is selected by user.

**Comment by urtson** [comment]
Requested fields should be in the form 'attach_link__collection' etc. Added these fields to config_add.

If needed, it could be possible to chain attach_link fields to create links to many objects e.g. for a data file that contains results of many analyses: attach_link__analysis=3450&attach_link__analysis=3451 etc.

One another thought about relations:
Attachment model has already direct ForeignKey fields to specimen, locality, drillcore and drillcore_box tables. Attachments can then have relations to e.g. locality either directly or through attachment link. Photo archive and specimen images right now use the direct relation which is ok when you have one object to link to. For other files ManyToMany relation may be needed.

Should we unify this somehow or is it ok? Regarding to queries that should look for the same object from different fields.

**Comment by ollehints** [comment]
Direct links to specimen, locality and drillcore_box are due to compatibility reasons when moving from 4 separate tables to only one.
In the future we should probably keep a direct link to specimen only. Others should move to standard many-to-many relation. At the moment, however, old code deptnds on these direct links.

**Comment by enmust** [comment]
Added relations

**Comment by urtson** [comment]
Attachment links are now created
