### ISSUE TITLE
Dashboard contents

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#20]
Header menu should say "Geocollections file management | Geokogude failihaldus" instead of "Tere $user"
Dashboard could show "Tere $user" as title, and then brief description: 
"Siin saab geokogude infosüsteemi kasutaja lisada ja parandada geoloogia ja kollektsioonidega seotud faile: fotoarhiivi pilte, kollektsioonieksemplaride pilte, skaneeritud publikatsioone, tabelkujul andmefaile jms. Kõik failid on seotud konkreetse kasutaja ning asutusega. Iga kasutaja saab siin näha ja muuta ainult enda autorlusega ja/või enda sisestatud faile, aga kõik failid, mis ei ole märgitud privaatseks, muutuvad avalikult nähtavaks geokogude portaalis: http://geocollections.info". 

"This application allows adding and editing files related to geology and geocollections, including photo archive, images of collection specimens, scanned publications, tabular data files etc. All files are linked to user and institution and each user can see and edit only the files he/she has authored and/or entered into the database. However, all files that are not marked as private will be publicly shown on geocollections portal at http://geocollections.info". 
 
Then buttons: [Add Photo] [Add specimen image] [Add other file] [Listand edit my files]

Then, maybe, display the last added file or files.

**Comment by enmust** [comment]
Done except the show last added file or files

**Comment by enmust** [comment]
Done
