### ISSUE TITLE
other file types

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#21]
* Other files section should allow other file types too: pdf, txt, xls, xlsx etc. Probably useful to allow all files and enforce restrictions when problems come. 
* Author could be empty for other files - for instance, if uploading a publication by someone not listed in agent table, or a drawing by an unknown author etc.
* Other files are not related to imageset - currently this limits saving. 
* Rating is not useful for non-image files.

**Comment by enmust** [comment]
- ~Other files section should allow other file types too: pdf, txt, xls, xlsx etc. Probably useful to allow all files and enforce restrictions when problems come.~
- ~Author could be empty for other files - for instance, if uploading a publication by someone not listed in agent table, or a drawing by an unknown author etc.~
- Other files are not related to imageset - currently this limits saving. - **Should I add imageset field?**
- ~Rating is not useful for non-image files.~

**Comment by urtson** [comment]
Imageset error fixed

**Comment by enmust** [comment]
Tested and uploading works
