### ISSUE TITLE
Reading EXIF data

### ISSUE THREAD

**Issue by urtson** [geocollections/sarv-file-upload#26]
From image EXIF data the coordinates and date created can be read. API can do that but only after saving the new attachment and uploading the file. The user does not see that these data are available.

It propose the data is read in Vue and displayed immediately as pre-filled fields right after choosing the file. User has then no need to type in the values.

This holds of course for single uploaded files. By multiple files it would be handled by API in the background during saving new records.

**Comment by ollehints** [comment]
Also camera model (device_txt) and pixel dimensions should be read from EXIF.
I am not sure how js can handle this but there are some libraries like https://github.com/exif-js/exif-js

**Comment by enmust** [comment]
Tried that library but it is very buggy and outdated. I saw image metadata using that library but couldn't extract it, because getData function is not working properly (a lot of open issues on github). Even tried changing source code but no luck.

**Comment by enmust** [comment]
now using meta data in photo archive. 

Currently extracting these fields: date, date_digitised, description, device

Also I am getting X and Y dimensions but I need to add those fields (image_width, image_height) back to upload object

Also I am getting GPS data but I need to format it properly to decimals

**Comment by enmust** [comment]
Done
