### ISSUE TITLE
Add photos - order of fields

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#27]
It would make sense to keep more relevant fields in the top. Thus: device, device text, agent digitised, device digitised, date digitised and image type should make the last 3 rows (before rating). keywords row should be before licence.

**Comment by ollehints** [comment]
same in specimen image: image desciption and keywords should come before device etc.

**Comment by ollehints** [comment]
same in files: description and keywords should come after date created free. and description and description en should both be required fields.

**Comment by enmust** [comment]
Done
