### ISSUE TITLE
Attachment link in change view (other files)

### ISSUE THREAD

**Issue by enmust** [geocollections/sarv-file-upload#28]
I can use these kind of requests to get related data
Specimen: 
https://rwapi.geocollections.info/attachment/1803?attach_link__specimen__id__isnull=false&fields=attach_link__specimen__id,attach_link__specimen__coll__number,attach_link__specimen__specimen_id&distinct=true
Sample: 
https://rwapi.geocollections.info/attachment/1?attach_link__sample__id__isnull=false&fields=attach_link__sample__id,attach_link__sample__number&distinct=true

That means 13 extra requests for every 'other file' change view. 
Should I start implementing it or is there a better way, for example through related_data?

**Comment by urtson** [comment]
I added attachment_link table to config.

https://rwapi.geocollections.info/attachment_link/?attachment=121440

**Comment by enmust** [comment]
Done
