### ISSUE TITLE
show original filename

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#33]
original filename should be shown alongside with filename, uuid etc.

**Comment by ollehints** [comment]
the read-only text should be in the this order:
- Filename : d8632364-ae2f-4723-ab08-abdf7eeb0d5b.jpg
- Original filename: 
- Attachment format value : image/jpg
- Image width : 6000
- Image height : 4000
- Date added : 3.6.2018
- User added : olle
- Date changed : 3.6.2018
- User changed : olle

**Comment by enmust** [comment]
Done
