### ISSUE TITLE
Related tables in change view

### ISSUE THREAD

**Issue by urtson** [geocollections/sarv-file-upload#42]
Change view should display current attachment_link objects

**Comment by ollehints** [comment]
i cannot get it saving values to attachment_link table. also -- user_added etc fields in attachment_link should be filled upon save.

**Comment by ollehints** [comment]
ok -- works when adding new attachment

**Comment by urtson** [comment]
Changing attachment links now works. As current links are not displayed in the form, they are also not sent to API and are deleted. This can be used for deleting fake links made for testing.
user_added is now saved too.

**Comment by enmust** [comment]
Now showing related links in change view
