### ISSUE TITLE
Unspecified attachment type in Other files 

### ISSUE THREAD

**Issue by urtson** [geocollections/sarv-file-upload#43]
If 'unspecified' is chosen for attachment type, it refers to ListAttachment object with id=0 and gives error 'The database backend does not accept 0 as a value for AutoField.'  Django can't handle this as it can not refer to object with id=0.
Simplest workaround is to exclude that choice in the combo. if left blank, it also means unspecified

**Comment by ollehints** [comment]
should be OK in MySQL, no id=0 there any more

**Comment by urtson** [comment]
Ok
