### ISSUE TITLE
Check if user is logged in

### ISSUE THREAD

**Issue by urtson** [geocollections/sarv-file-upload#47]
API now returns 'error_not_logged_in' message in json when user is not logged in. This can be used for checking the current session in frontend.

**Comment by enmust** [comment]
Is there some kind of special request for it like .../is_logged_in or is it just returned with regular requests like  .../attachment/1

**Comment by urtson** [comment]
Error is returned by any request. Currently only by GET requests, /add and /change give 'Operation not permitted'. I should change that too as user can continue from any page and should be redirected to login form

**Comment by enmust** [comment]
Done
