### ISSUE TITLE
Error messages should stay visible

### ISSUE THREAD

**Issue by urtson** [geocollections/sarv-file-upload#48]
Error messages should be visible until user clicks them to close

**Comment by urtson** [comment]
Reopened this because new behaviour seems not convenient and we have to redesign this. It is unconvenient to click every error message.
The special case where we need to keep open the message is by specimen image upload when linking to specimen was not successful so the user can keep the list of files and correct the issues.
Is it possible to keep open only certain error messages with some special key? 
I can rename this special error 'link_error' for example so it can be distinguished from other errors.

**Comment by urtson** [comment]
For example, if session expires (200 min or do logout in API) then the 'error_not_logged_in' is thrown by any request while the user is redirected to login page. Interestingly, refreshing 'My files' page makes two requests and two messages are displayed accordingly

**Comment by enmust** [comment]
Well I can show error message which can only be closed by clicking on it. 
![image](https://user-images.githubusercontent.com/14908993/42205159-512ea638-7eac-11e8-96ec-01e5877af920.png)

**Comment by urtson** [comment]
Renamed link error to 'link_error' which should then stay open.

I prefer that 'error_not_logged_in' is shown briefly and not kept open like it was before. The message text should be 'Session expired. Please log back in.' Text should be coded in vue as the text returned by API is meaningful only when accessing API directly.

**Comment by enmust** [comment]
Updated

**Comment by enmust** [comment]
Reopen if needs fixing
