### ISSUE TITLE
implement map control

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#50]
Implement map control for selecting lat/long coordinates for photos during insert and for displaying the point on map after save. map could open in new window to save space in the main form.

**Comment by enmust** [comment]
js map https://leafletjs.com/

**Comment by ollehints** [comment]
- If coordinates are present in existing record, then the map should zoom in and show a marker. 
- Better make the map 100% wide content as the white space on margins is not useful. 
- Map accordion should be closed by default but the link for opening it should be more prominent (just bold or perhaps toggle button after longitude fields).  
- cursor should become crosshair while on the map.

**Comment by ollehints** [comment]
More -- users may need a satellite image option for global view and a more precise map for Estonia, preferably Maa-amet orthophoto like used in turvas.geokogud.info. The problem is -- coordinate systems differ.
