### ISSUE TITLE
Do not use related data for files related to other data objects

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#53]
Related data does not apply is_private filter and thus the existence of related files is shown even if the file is private. e.g., http://geocollections.info/reference/7806 -- linked file is private and should not be listed. The same problem occurs elsewhere. Eventually should be solved at API level.

**Comment by enmust** [comment]
Yes this should be solved at API level. Only thing I can do is add if clause to geocollections.info portal that only shows data if is_private is false.

**Comment by enmust** [comment]
Fixed it, reference view is not showing private files anymore
