### ISSUE TITLE
Implement selection of current user for admins

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#54]
In order to check and correct problems, admins should be able to see other author's files by somehow turning into other user.

**Comment by enmust** [comment]
First of all I would need to know how to identify user as admin. 

Then if I know user has admin rights I can add a new field 'author' to main search which then lets admins search and edit data which does not belong to them. (Basically overrides default search url using name and id from author field)

**Comment by urtson** [comment]
User could be checked by query '/user?username=user&is_admin=true' that returns count=1 or 0
Not implemented yet, have to add 'is_admin' column to sarv user table.

Though, 'is _superuser' is present in django auth_user table but accessing it needs some exceptions to be created in API

Could this query be a security issue as anyone can get all users with admin rights and then point attacks through these accounts?

**Comment by ollehints** [comment]
no information on usernames should be accessible publicly.
currently usernames are shown in some places  (user_added / user_changed), but in future this should be addressed.

**Comment by enmust** [comment]
Yes this could be a possible security problem if someone could find out admin users and start for example dictionary attacking login screen or something. 

Fortunately only authenticated users can use the API but still.
