### ISSUE TITLE
User warning on multi file upload

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#66]
Currently only 10 files can be uploaded at once on the server side. However, more files may be dragged to the upload button. Then the previews of e.g. 20 files are shown, and user expects all is OK, but only 10 files will actually be uploaded. Perhaps 10 is OK for the testing period, later we can increase the number. However, user should not be able to drag/select more files than accepted by server. And a warning should be shown if user attempts to upload more files: "Currently up to 10 files can be uploaded at once" / "Süsteem lubab korraga üles laadida kuni 10 faili".

**Comment by urtson** [comment]
Fixed it, API now returns error and does not upload. Perhaps specify the limit in tooltip under the file upload field?
