### ISSUE TITLE
API messages in Estonian

### ISSUE THREAD

**Issue by urtson** [geocollections/sarv-file-upload#67]
Currently API returns error or success messages only in English. Messages should be in Estonian when UI is switched to Estonian.
I can extend the message dictionary to contain messages in both languages and right one is chosen in javascript: {'error_en':'Some error','error_et':'Mingi viga'}
Any better idea?

**Comment by enmust** [comment]
Fine by me, currently some requests return message, maybe this should also be message_en and message_et then.

**Comment by urtson** [comment]
Added some error_et and message_et 's where information is important for the user. English ones left as they were.

**Comment by enmust** [comment]
Updated app and now wherever 'message' or 'error' was used I added Estonian variants

**Comment by enmust** [comment]
Also API side needs some estonian translations for example logging in and out

**Comment by urtson** [comment]
Added estonian messages for logging in and out
