### ISSUE TITLE
style of rating field

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#70]
Image rating UI control should be changes to something less dominating and probably smaller. Maybe just combo with predefined values:
NULL - not rated | hinnang puudub
1 - poor image | kehv pilt/objekt
2 - satisfactory image | rahuldav pilt/objekt
3 - good image/object | hea pilt/objekt
4 - very good image/object | väga hea pilt/objekt
5 - outstanding image/object | silmapaistev pilt/objekt

**Comment by enmust** [comment]
I was thinking changing it to checkboxes then but should there be an option for 'null' value also?

**Comment by enmust** [comment]
or did you mean select box like in pagination

**Comment by enmust** [comment]
Popups wouldn't work very well on mobile

**Comment by enmust** [comment]
Changed it to default select box same like changing page size in pagination.
