### ISSUE TITLE
some records cannot be edited

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-file-upload#76]
Some records cannot be edited for unknown reasons: https://upload.geocollections.info/#/edit/124763
Worked alright previously and correct data comes from API.

![image](https://user-images.githubusercontent.com/14974887/48054248-7b5fb480-e1b5-11e8-8130-f95584699b59.png)

**Comment by enmust** [comment]
This is digitised reference (specimen_image_attachment=4). It is work in progress #73
